[target.wasm32-unknown-unknown]
rustflags = [
    "--cfg=web_sys_unstable_apis",
    "-C",
    "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "-C",
    "link-args=--shared-memory --import-memory",
]

[unstable]
build-std = ["panic_abort", "std"]
